version: '3'
services:
  userservice:
    container_name: userservice
    image: local-user-service:latest
    restart: always
    volumes:
      - ${HOME}/Projects/egovframe-msa/egovframe-msa-edu/:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://192.168.100.16:8888
      SPRING_PROFILES_ACTIVE: default
      APP_HOME: /usr/app
      EUREKA_INSTANCE_HOSTNAME: 192.168.100.16
      MYSQL_HOSTNAME: 192.168.100.16
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TZ: Asia/Seoul

  boardservice:
    image: local-board-service:latest
    restart: always
    volumes:
      - ${HOME}/Projects/egovframe-msa/egovframe-msa-edu/:/usr/app/msa-attach-volume
    environment:
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      SPRING_CLOUD_CONFIG_URI: http://192.168.100.16:8888
      SPRING_PROFILES_ACTIVE: default
      APP_HOME: /usr/app
      EUREKA_INSTANCE_HOSTNAME: 192.168.100.16
      MYSQL_HOSTNAME: 192.168.100.16
      RABBITMQ_HOSTNAME: rabbitmq
      TZ: Asia/Seoul
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"

  portalservice:
    container_name: portalservice
    image: local-portal-service:latest
    restart: always
    volumes:
      - ${HOME}/Projects/egovframe-msa/egovframe-msa-edu/:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://192.168.100.16:8888
      SPRING_PROFILES_ACTIVE: default
      APP_HOME: /usr/app
      EUREKA_INSTANCE_HOSTNAME: 192.168.100.16
      MYSQL_HOSTNAME: 192.168.100.16
      RABBITMQ_HOSTNAME: rabbitmq
      TZ: Asia/Seoul

networks:
  default:
    external:
      name: egov-network