version: '3.2'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    environment:
      TZ: Asia/Seoul

networks:
  default:
    external:
      name: egov-network