version: '3.2'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      TZ: Asia/Seoul

networks:
  default:
    external:
      name: egov-network